### ISSUE TITLE
no pages version for 1.4.0 :-(

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Pages#50] opened 2015-09-15 19:17 UTC
I tried 2.6.0 (with increased version number for core) what is not installable (as expected). The current master ist also not installable at 1.4.0

Unfortunately no version for 1.4.0 is available

**Comment by craigh** [comment] 2015-09-16 01:30
try this: https://github.com/zikula-modules/Pages/releases/tag/2.7.0

warning: I have not tested it at all.

**Comment by craigh** [comment] 2015-09-18 12:24
@rallek did you try it?

**Comment by rallek** [comment] 2015-09-18 12:31
No. Hope I will find the time this weekend

**Comment by rallek** [comment] 2015-09-18 16:04
tried it right now.

Used command line. Moved into modules folder, download zip via wget, unpacked 2.7.0.zip, renamed the folder Pages-2.7.0 to Pages.

Went to my zikula installation. Found in the extensions a Modules named ZikulaPagesModule. Activation gives the following error:


Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

An exception occurred while executing 'INSERT INTO pages (title, metadescription, metakeywords, urltitle, content, counter, displaywrapper, displaytitle, displaycreated, displayupdated, displaytextinfo, displayprint, language, cr_uid, cr_date, lu_uid, lu_date, obj_status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["Welcome to Pages content manager", "", "", "welcome-to-pages-content-manager", "This is a demonstration page. You can use Pages to create simple static content pages. It is excellent if you only need basic html for your pages. You can also utilize the Scribite module for WYSIWYG content creation. It is well suited for informational articles, documents and other \"long term\" type content items.<br \/><br \/>Pages is a hookable module which allows you to hook EZComments or other hook providers to extend the capabilities of your module.", 0, null, null, null, null, null, null, "de", 2, "2015-09-18 17:59:51", 2, "2015-09-18 17:59:51", "A"]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'displaywrapper' cannot be null

**Comment by craigh** [comment] 2015-09-18 18:08
hanks for trying. I will look into it.

**Comment by craigh** [comment] 2015-09-28 20:48
I have been looking into this for several hours over a couple days and don't know what to do. I cannot figure out a way to make a 1.4.0 compatible release of Pages! The best I have found is 2.5.1 and that doesn't work either. Pages was a mess and all my refactoring to make it compatible with the current core has left it incompatible with past core releases, including 1.4.0! believe me I am as frustrated as everyone else. I don't know how, but the version in use at zikula.org is _working_ but even a clone at that same commit won't work on 1.4.0 (there are some issues with that version there as well - like the search issue). So I'm not sure what to do. Certainly, when 1.4.1 is released we can be sure to have a compatible version. It is embarrassing at best though that we have no static page module available for 1.4.0. Maybe someone else can do something with this? @cmfcmf @Guite @Kaik @phaidon help!

**Comment by rallek** [comment] 2015-09-29 04:45
Work on 1.4.1. There are more or less no 1.4.0 sites made. Evrybod is waiting for 1.4.1 or even later to have a more stable version. I can live with this situation.

**Comment by Guite** [comment] 2015-09-29 05:57
Yes! 1.4.1 is more important than backporting Pages master.

**Comment by MrMontesa** [comment] 2015-09-29 11:49
Just stumbled upon the same issue, when trying to upgrade Pages from 2.6.0 to latest from github.
More an FYI. I can wait for zk 1.4.1

**Comment by nmpetkov** [comment] 2015-09-29 19:17
I also made some tests.
I found current Github files from Pages 2.6 branch are installable and can work somehow in Zikula 1.3.10 installation (Pages version 2.6.1).
Then, I tried same files, changing line ```$meta['core_max'] = '1.3.99';```  to ```$meta['core_max'] = '1.4.99';```, and I managed to install the module in Zikula 1.4.0 installation.
Then going to Pages admin page I received error:
``` Fatal error: Call to undefined method Doctrine\ORM\Query\AST\PathExpression::isSimpleArithmeticExpression() in /home/xyz/public_html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php on line 2145```
Front end seems to work properly.

So, I suggest to work on Pages 2.6. branch to make it compatible with Zikula 1.4 (and in Zikula 1.3.10), as any other module can.

**Comment by Kaik** [comment] 2015-11-02 12:21
Hi, above error "Integrity constraint violation: 1048 Column 'displaywrapper' cannot be null" this is because displaywrapper is not set and this happen when default example page is added into the db during activation. Two ways of solving this problem either change table to allow null for that column or update installer to set displaywrapper. This is just from looking on error I have not looked into code yet.
Fields to fill:
title,
metadescription,
metakeywords, 
urltitle, 
content, 
counter, 
displaywrapper,
displaytitle,
displaycreated,
displayupdated,
displaytextinfo,
displayprint,
language,
cr_uid,
cr_date,
lu_uid,
lu_date,
obj_status

Your data:
"Welcome to Pages content manager",
 "",
 "",
"welcome-to-pages-content-manager",
 "This is a demonstration page. You can use Pages to create simple static content pages. It is excellent if you only need basic html for your pages. You can also utilize the Scribite module for WYSIWYG content creation. It is well suited for informational articles, documents and other \"long term\" type content items.

Pages is a hookable module which allows you to hook EZComments or other hook providers to extend the capabilities of your module.",
 0, 
null, 
null, 
null, 
null, 
null, 
null, 
"de", 
2, 
"2015-09-18 17:59:51", 
2, 
"2015-09-18 17:59:51", 
"A"
All the ones that are null might cause similar error.
Let me look into code :)

**Comment by pheski** [comment] 2015-11-10 12:04
I can confirm that Pages will not work in 1.4 (hope 1.4.1 comes soon) - I get the following error:
I just tried installing Pages into a fresh 1.4 and got this error when I tried to go to Extensions:

Fatal error: Class 'ZikulaPagesModulePagesModuleVersion' not found in /home/hermannhesse/pheski.com/system/Zikula/Module/ExtensionsModule/Api/AdminApi.php on line 510
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Attempted to load class "PagesModuleVersion" from namespace "ZikulaPagesModule". Did you forget a "use" statement for another namespace?

**Comment by rallek** [comment] 2015-12-06 13:11
since 1.4.1 is availabe and pages is working there we can close this issue

**Comment by craigh** [comment] 2015-12-06 13:11
I've not tested at all. It installs, works, uninstalls?

**Comment by rallek** [comment] 2015-12-06 13:22
I thought it is working fine. install and uninstall is fine but working not. See https://github.com/zikula-modules/Pages/issues/51

**Comment by nmpetkov** [comment] 2015-12-13 19:11
As continuation of my post above, I tested again Pages branch 2.6 (from Github), this time with fresh installation of Zikula 1.4.1. I found same error as I posted before.

After some debugging, I found that used paginator is the problem. The error occurs in this line:
https://github.com/zikula-modules/Pages/blob/2.6/lib/Pages/Access/Pages.php#L112

After commenting this lines (switching off pagination), the module works at all, tested main features and hooking with Scribite.

**Comment by craigh** [comment] 2015-12-13 19:18
I've just been working on this - like RIGHT NOW.

I've established a branch https://github.com/zikula-modules/Pages/tree/core-141-compat which is currently working with Core-1.4.1 (only). I know of at least two issues I haven't solved yet:
1. hooks don't error, but don't function (and only from subscriber atm)
2. Categories selector is bad, but this has been true since I was working on it a while ago.

@nmpetkov  The paginator is a problem with 1.4.0 and can't be fixed without an update to 2.6 - so using my new branch seems the best option, IMO. I think this one uses the new paginator. I would be interested to know if that works for you.

the hooks problem cannot be fixed in pages from the provider side - this will take a core update from what I can see. I need to look into it more.

I also have some ideas for the category thing based on some recent work I did in the BlocksModule, but haven't fixed it yet.

Anyway - let's work on this branch https://github.com/zikula-modules/Pages/tree/core-141-compat and see what can be fixed here and release a Pages module for 1.4.1 ASAP. I'll plan to work on the two issues I mentioned.

**Comment by craigh** [comment] 2015-12-15 21:50
OK - so I have a version of this that is working with 1.4.1 (as far as I can tell). The major problem is that the Core-1.4.x Category stuff is a mess and not working. I think I have that fixed for 1.4.2 but obviously this doesn't solve the immediate problem.

So what I have done is disabled the category stuff in the 1.4.1-compatible version of pages and it works but obviously the categories cannot be assigned to pages. Existing pages maintain their current category relation but new pages cannot be related. Nor can the admin view be filtered by category.

My question to you @nmpetkov @rallek @Kaik @pheski @cmfcmf @Guite is whether this is valuable or not - e.g. should it be released. If so, I will finalize what I have and release a Core-1.4.1 compatible version of pages. Please respond ASAP.

**Comment by craigh** [comment] 2015-12-15 23:46
HA! I'm a moron. I fixed the categories issue. All I had to do was move the classes into Pages. lol. I must be tired.

**Comment by craigh** [comment] 2015-12-15 23:58
please test this [v3.0.0-beta](https://github.com/zikula-modules/Pages/releases/tag/v3.0.0-beta1)

**Comment by nmpetkov** [comment] 2015-12-16 12:05
I tested Pages v3.0.0-beta with fresh Zikula 1.41 installation + Scribite 5.0.1-beta1.

1. New Pages installation: Ok.
2. New Scribite 5.0.1-beta1 installation: Ok.
3. Hook Scribite to Pages: Ok.
 (A side comment: Here I hooked Scribite also to Blocks module, to see if HTML edit works with visual editor enabled - NOT WORKING!).
4. Edit the sample page: Ok.
  Comment 1: Edit title and other fields works. Visual editor is activated (hook to Scribite works).
  Comment 2: Visual editor also is activated for Metadescription and Metakeywords fields, which is not desired. It needs to add ```cssClass='noeditor' ``` to input text plugin to fix this.
5. Create new page: Ok
6. Pager in Admin panel: Not working.

  Comment 1: I made 4 pages and in Pages Config I set Items per page = 2. Pager appears, but clicking on page 2 shows page 1.
  Comment 2 : I found the reason. In address bar of the browser I see:
![image](https://cloud.githubusercontent.com/assets/628801/11840156/2375b976-a3fc-11e5-84f0-cb560c626673.png)
  Note ``` &amp; ``` instead of &
  Comment 3: Note  the existence of the word ``` zikulapagesmodule ``` in address bar, IMO ``` pages ``` is better to be the default.
7. Click on preview button in admin pages list for a page: Error
![image](https://cloud.githubusercontent.com/assets/628801/11840366/0a466fd4-a3fe-11e5-825e-872f3c5f17de.png)

FRONTEND

1. I make pages option in main menu, using ``` {Pages} ```.
2. Clicking in frontend on this option shows categories in Pages: Ok.
![image](https://cloud.githubusercontent.com/assets/628801/11840255/0c11e024-a3fd-11e5-850a-e83c0f2b01b9.png)
3. Clicking on ``` Category 1 ``` displays error:
![image](https://cloud.githubusercontent.com/assets/628801/11840290/4caf2196-a3fd-11e5-8df3-03c6af4ba136.png)

**Comment by craigh** [comment] 2015-12-16 13:09
The HtmlBlock <--> Scribite hook won't work with 1.4.1 because the data is not updated like it should be (in the DB< the key is 'Html' and it should be 'HtmlBlock')> if you create a *new* Html block you will see it works because the key is correct. This will be corrected in 1.4.2

**Comment by craigh** [comment] 2015-12-16 15:53
I've now fixed the pager links and also updated filter and sortable column headers to work properly.

**Comment by craigh** [comment] 2015-12-16 16:00
beta2 released: https://github.com/zikula-modules/Pages/releases/tag/v3.0.0-beta2

**Comment by nmpetkov** [comment] 2015-12-17 09:44
I tested Pages v3.0.0-beta2 and filter and pager now work. I continue to obtain error in fronend and clicking preview icon:
![image](https://cloud.githubusercontent.com/assets/628801/11866237/6f8340c0-a4b2-11e5-9b9a-b080da96a838.png)
In the browser address bar I have:
![image](https://cloud.githubusercontent.com/assets/628801/11866264/96d58c32-a4b2-11e5-9cea-db8ef1127b63.png)

**Comment by craigh** [comment] 2015-12-17 12:26
I cannot reproduce this problem :disappointed:

**Comment by nmpetkov** [comment] 2015-12-17 12:35
I've just found that if deactivate multilingual settings in Localization settings, then the problem disappears.

**Comment by craigh** [comment] 2015-12-17 12:41
hmmm. that makes it sound like https://github.com/zikula/core/issues/2672 but this isn't an ajax route.

**Comment by craigh** [comment] 2015-12-17 12:46
![screen shot 2015-12-17 at 7 45 50 am](https://cloud.githubusercontent.com/assets/350048/11870048/4a03cbbe-a492-11e5-9f47-92f732e9cd8c.png)
But I have multilingual enabled and it works.

**Comment by craigh** [comment] 2015-12-17 12:49
screenshot your whole list please.

**Comment by craigh** [comment] 2015-12-17 12:50
never mind.

**Comment by nmpetkov** [comment] 2015-12-17 12:54
I'll make test again from zero without second language, and will report here at which stage the error occurs.

**Comment by nmpetkov** [comment] 2015-12-17 13:24
Ok, I found how to reproduce the error. 
Install second language, save main settings (multilingual on - this is the defaultt), then install language switcher block (to be able to switch languages). 
Switch to second language (other then English). Then try to go to module admin panel and click on preview icon, or go to front end and try to enter the module.

**Comment by craigh** [comment] 2015-12-17 13:27
please copy and paste one of the preview links here.

**Comment by craigh** [comment] 2015-12-17 13:29
also copy and paste the error.

**Comment by nmpetkov** [comment] 2015-12-17 13:31
Address on preview icon is always same:
http://xyz.com/pages/display/welcome-to-pages-content-manager

The error is same as I posted earlier:

Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("urltitle") to generate a URL for route "en__RG__zikulapagesmodule_user_display".") in "ZikulaAndreas08Theme:Body:2col.html.twig" at line 3.

**Comment by nmpetkov** [comment] 2015-12-17 13:35
In addition - again if I now disable multilingual option in Localization settings, then error disappears.

**Comment by craigh** [comment] 2015-12-17 13:59
@nmpetkov IMO this is a bug with the core Language block, not with pages.

The language block is old tech - probably 1.2-era. and operates on the old principles of translation. I doubt it has been updated to work in the new 'symfony' way.

The error you are receiving is because the language block is not capable of generating the proper link for the page. Someday this is correctible but not within pages.

the only solution at the moment is to disable the block.

**Closed by craigh** 2015-12-17 13:59 UTC
Labels: Bug

**Comment by craigh** [comment] 2015-12-17 14:12
FC1: https://github.com/zikula-modules/Pages/releases/tag/v3.0.0-fc1

**Comment by nmpetkov** [comment] 2015-12-17 14:25
In all beta, and in v3.0.0-fc1, there is one small bug: in frontend after clicking in empty category (Catgory 2 is empty when installing Pages for example), then instead an empty list, we receive:
```
The server returned a "500 Internal Server Error".
```

**Comment by craigh** [comment] 2015-12-17 14:45
I'm looking into this. in the future, please open a new ticket.

**Comment by craigh** [comment] 2015-12-17 15:02
@nmpetkov I cannot reproduce.

I created a new category which is obviously empty. Then in frontend:

![screen shot 2015-12-17 at 10 01 21 am](https://cloud.githubusercontent.com/assets/350048/11872794/3235ba0c-a4a5-11e5-80f4-0a680ee59ea8.png)

clicking on Category3 results in:

![screen shot 2015-12-17 at 10 01 30 am](https://cloud.githubusercontent.com/assets/350048/11872799/3d65ba80-a4a5-11e5-8076-1022efaf506f.png)

**Comment by nmpetkov** [comment] 2015-12-17 15:12
Ok, it is possible to happen to me only. Let wait if somebody else will report, it is not so important.

**Comment by pheski** [comment] 2016-05-29 18:49
I confirm - cannot install Pages 3.0.0 on Zikula 1.4.2

An exception occurred while executing 'INSERT INTO pages (title, metadescription, metakeywords, urltitle, content, counter, displaywrapper, displaytitle, displaycreated, displayupdated, displaytextinfo, displayprint, language, cr_date, lu_date, obj_status, cr_uid, lu_uid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["Welcome to Pages content manager", "", "", "welcome-to-pages-content-manager", "This is a demonstration page. You can use Pages to create simple static content pages. It is excellent if you only need basic html for your pages. You can also utilize the Scribite module for WYSIWYG content creation. It is well suited for informational articles, documents and other \"long term\" type content items.<br \/><br \/>Pages is a hookable module which allows you to hook EZComments or other hook providers to extend the capabilities of your module.", 0, 1, 1, 1, 1, 1, 1, "en", null, null, "A", null, null]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'cr_date' cannot be null
