### ISSUE TITLE
Can't create new page (with xinha in Scribite)

### ISSUE THREAD

**Issue by pheski** [zikula-modules/Pages#52] opened 2015-12-20 16:47 UTC
Installed Pages (Z 1.4.1) and created a test page. Worked fine.

Tried to use the globule modules categories for Pages - no joy

Then reverted to mapping Pages to the categories it included - now when I try to create a new page I get this pop-up error: "Please fill out this field" at the top of the screen, but it doesn't tell me what field it thinks is missing.

P

**Comment by pheski** [comment] 2015-12-20 17:03
So, just to be clear, what I would LIKE to do is use the global module categories for Pages, but that seems not to work.

**Comment by rallek** [comment] 2015-12-20 17:47
I tried to confirm. I can only confirm a small issue.
I do have a 1.4.1 site with pages and scribite. I changed the pages categories to global. I can add a new page. If I select a category it si not shown up. But in the table pages_categories I do see the entries.

**Comment by craigh** [comment] 2015-12-20 23:39
> Tried to use the globule modules categories for Pages

what do you mean? can you be more specific in describing what you did?

Did you keep or delete the page originally assigned to existing categories?

**Comment by craigh** [comment] 2015-12-20 23:58
> If I select a category it si not shown up.

@rallek what do you mean? where?

**Comment by craigh** [comment] 2015-12-21 00:03
I just installed Pages (which creates a default page in Category 1) then immediate adjusted the category registry to point Pages to Global categories instead of Pages.

In Admin view, the default page still indicates Category 1. The filter lists the global categories.

Create a new page select a global category, works fine. View page which indicates selected global category.

Go to user view (`pages/categories`) and see list of global categories. The category I picked indicates ` page. Click on the category, it lists my page. click on my page, all is well.

Go back to default page, edit. select no category. save. admin list view now indicates "no category" for the default page. Can view from admin list but (obviously) no listed in the user categories view.

It all works for me as I would expect. please tell me how to reproduce the behavior you are seeing.

**Comment by pheski** [comment] 2015-12-21 00:51
I installed Pages in Zikula 1.4.1.

Pages created its own Categories 1 and 2, so the tree looked like this:

Root
---Modules
--------Global
-------------A list of global categories
--------News Publisher
--------Pages
-------------Category 1
-------------Category 2

Initially I thought I would save myself work and use the same set of categories I built under global, so I used Category Registry to link Static Pages to  	

/__SYSTEM__/Modules/Global

instead of:

/__SYSTEM__/Modules/ZikulaPagesModule (using PageEntity)

I was able to create one page, but since that time, every time I try to create a page, when I get to save, I get the 'Please fill out this field' pop-up.

P

**Comment by pheski** [comment] 2015-12-21 01:07
More info.

I uninstalled Pages and re-installed it and had no trouble linking it to global categories using category registry.  I then had no trouble adding 5 static pages in different categories.

THEN I added the Scribite hook - and immediately started getting the pop-up about the unfilled field.  Using xinha as my default Scribite set.

**Comment by pheski** [comment] 2015-12-21 01:15
CKEditor works fine. I haven't tested all the editors, but given that this works fine with CKEditor, I assume the problem has to do with something xinha is throwing. Have changed title of this thread to reflect that. Other things to do right now so will not test all the editors...:-)

**Comment by craigh** [comment] 2015-12-21 01:27
Xinha is crap. don't use it.

**Comment by pheski** [comment] 2015-12-21 01:30
Nor do I, anymore :+1: 

CKEditor seems easy and seems to work based on my 20 minutes so far.

**Comment by craigh** [comment] 2015-12-21 12:56
closing as seems to be an editor issue, not Pages.

**Closed by craigh** 2015-12-21 12:56 UTC
