### ISSUE TITLE
pages can not be installed for Zikula 1.4.2

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Pages#56] opened 2016-04-24 15:35 UTC
I tried `master` and `v3.01` as well. In both cases I do get the following error:

```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

An exception occurred while executing 'INSERT INTO pages (title, metadescription, metakeywords, urltitle, content, counter, displaywrapper, displaytitle, displaycreated, displayupdated, displaytextinfo, displayprint, language, cr_date, lu_date, obj_status, cr_uid, lu_uid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["Welcome to Pages content manager", "", "", "welcome-to-pages-content-manager", "This is a demonstration page. You can use Pages to create simple static content pages. It is excellent if you only need basic html for your pages. You can also utilize the Scribite module for WYSIWYG content creation. It is well suited for informational articles, documents and other \"long term\" type content items.<br \/><br \/>Pages is a hookable module which allows you to hook EZComments or other hook providers to extend the capabilities of your module.", 0, 1, 1, 1, 1, 1, 1, "en", null, null, "A", null, null]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'cr_date' cannot be null
```

I do have a german language pack installed for zikula (uncomplete). I switched off the language settings and choose english as standard. No change.

It seem to be similar to #50 

It is a fresh install of zikula 1.4.2 plus scribite and content.

**Comment by pheski** [comment] 2016-05-29 18:49
I can confirm: cannot install (on a fresh Zikula 1.4.2) Pages with master, 3.0.0 and cannot install, with the following error message:

An exception occurred while executing 'INSERT INTO pages (title, metadescription, metakeywords, urltitle, content, counter, displaywrapper, displaytitle, displaycreated, displayupdated, displaytextinfo, displayprint, language, cr_date, lu_date, obj_status, cr_uid, lu_uid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["Welcome to Pages content manager", "", "", "welcome-to-pages-content-manager", "This is a demonstration page. You can use Pages to create simple static content pages. It is excellent if you only need basic html for your pages. You can also utilize the Scribite module for WYSIWYG content creation. It is well suited for informational articles, documents and other \"long term\" type content items.<br \/><br \/>Pages is a hookable module which allows you to hook EZComments or other hook providers to extend the capabilities of your module.", 0, 1, 1, 1, 1, 1, 1, "en", null, null, "A", null, null]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'cr_date' cannot be null

**Comment by Guite** [comment] 2016-05-30 06:08
Which MySQL version do you use?

**Comment by pheski** [comment] 2016-05-30 12:25
5.6.25 based on a SQL select version () query.

Would/could this be related to InnoDB vs MyISAM? My host currently defaults to InnoDB which is what I am using, though I have the options of using MyISAM. The documentation in 1.4.2 does not address this that I can see.

Peter

**Comment by detlefmue** [comment] 2016-10-18 14:35
I get the same error like @pheski: 

> Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE pages

Zikula - 1.4.3
Pages - 3.0.1

Question: Where must Pages be located?
[A] /modules/Pages or
[B] /modules/zikula/pages-module

**Comment by detlefmue** [comment] 2016-10-18 14:52
Tested to delete the existing tables pages and pages_categories. Now I get this error:
`
An exception occurred while executing 'INSERT INTO pages (title, metadescription, metakeywords, urltitle, content, counter, displaywrapper, displaytitle, displaycreated, displayupdated, displaytextinfo, displayprint, language, cr_date, lu_date, obj_status, cr_uid, lu_uid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["Welcome to Pages content manager", "", "", "welcome-to-pages-content-manager", "This is a demonstration page. You can use Pages to create simple static content pages. It is excellent if you only need basic html for your pages. You can also utilize the Scribite module for WYSIWYG content creation. It is well suited for informational articles, documents and other \"long term\" type content items.<br \/><br \/>Pages is a hookable module which allows you to hook EZComments or other hook providers to extend the capabilities of your module.", 0, 1, 1, 1, 1, 1, 1, "de", null, null, "A", null, null]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'cr_date' cannot be null`

**Comment by nmpetkov** [comment] 2016-10-19 12:37
I tested Pages (current state from master branch), with fresh install of Zikula 1.4.3.
I obtained same error, and obviously it is because it is not given data for "cr_date" field.
So, I commented line:
``` $this->createIntroPage(); ```
In file PagesModuleInstaller.php.

Then module install in proper way (without itro page), and works at all (create page, view page and other).

**Comment by craigh** [comment] 2016-10-19 13:12
> and works at all

do you mean that it **DOES** work or **DOES NOT** work? (I think something lost in translation here)

**Comment by nmpetkov** [comment] 2016-10-19 13:19
Sorry for misunderstanding - "at all" here means "works for things I tested, but I did't tested all features in the module".

**Comment by detlefmue** [comment] 2016-10-19 17:51
I commented the same line in PagesModulInstaller.php as mentioned above ..

Now I get this error ...
`Class 'Zikula\PagesModule\Entity\CategoryEntity' does not existInitialization of ZikulaPagesModule failed! `

**Comment by nmpetkov** [comment] 2016-10-19 20:06
@detlefmue try to delete 2 tables from unsuccessful installation (pages and pages_categories) before to install again, and manually remove all other traces from pages in hooks zikula tables.

**Comment by nmpetkov** [comment] 2016-10-19 20:07
Also empty /app/cache directory.

**Comment by detlefmue** [comment] 2016-10-19 20:38
Tried all, but it doesn't work, same error message again.

**Comment by detlefmue** [comment] 2016-10-23 11:10
Tried once more on a total clean Zikula 1.4.3 .. regarding the change by @nmpetkov . 

Get the same error message ..

`Class 'Zikula\PagesModule\Entity\CategoryEntity' does not existInitialization of ZikulaPagesModule failed!` :(

**Comment by nmpetkov** [comment] 2016-10-23 17:55
@detlefmue
Some more info:
At the moment I can not install again Zikula, but I uninstalled module Page - it was without propblems.
Then I checked - no traces from pages in database (pages and pages_category tables was deleted, in hook tables no records with pages connection.
Then I installed Pages - no errors, empty table.

Once again:
Zikula 1.4.3
Pages - current state from Github.
One change (see picture below):
![image](https://cloud.githubusercontent.com/assets/628801/19628259/89c54636-9962-11e6-9b11-fd1e055dc79c.png)

I can suggest to change to debug mode, and to try again - to provide full trace of the error you obtained.
To change to debug mode, open file:
app/config/custom_parameters.yml
and change 
``` debug: true ```

**Comment by detlefmue** [comment] 2016-10-23 18:50
@nmpetkov 
Done it. But I get the same error message - not a word more.

**Comment by nmpetkov** [comment] 2016-10-23 18:57
BTW - your error seems is connected with pages category table. I don't know what this table doing here - it is new to this release in Pages module, In my Zikula 1.3 sites it is missing.

**Comment by nmpetkov** [comment] 2016-10-23 19:02
@detlefmue About debug mode: before editing app/config/custom_parameters.yml, you have to change read only attributes to gain write access.

**Comment by detlefmue** [comment] 2016-10-23 19:18
This category table is a mystery to me too. Zikula has a category system and the pages module uses it. Don't know why this table is there.

I got the file custom_parameters.ymledited without problems.

**Comment by craigh** [comment] 2016-12-09 12:54
@nmpetkov @detlefmue please test with Core-1.4.4

**Comment by craigh** [comment] 2016-12-09 12:55
also @Kaik @rallek 

please use the latest build

https://github.com/zikula-modules/Pages/archive/master.zip

**Comment by craigh** [comment] 2016-12-09 12:56
and @pheski

**Comment by Guite** [comment] 2020-05-07 06:39
Closing since this issue is outdated and Pages 4.0.0 provides a complete rewrite.

**Closed by Guite** 2020-05-07 06:39 UTC
